name: Deploy to Self-Hosted Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4    

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Application
      run: dotnet build --configuration Release --no-restore

    - name: Publish Application
      run: dotnet publish -c Release -o ${{ secrets.DEPLOY_PATH }}

    # - name: Restart IIS
    #   run: |
    #     Stop-Service -Name W3SVC
    #     Start-Service -Name W3SVC
