name: Deploy to Self-Hosted Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4    

    - name: Restore Dependencies
      run: dotnet restore Qoip/Qoip.sln

    - name: Install npm dependencies
      working-directory: Qoip/Qoip-Web/wwwroot
      run: npm install

    - name: Build TypeScript
      working-directory: Qoip/Qoip-Web/wwwroot
      run: npm run build  

    - name: Build Solution
      run: dotnet build Qoip/Qoip.sln --configuration Release --no-restore

    - name: Take Application Offline
      run: New-Item -Path "${{ secrets.DEPLOY_PATH }}/app_offline.htm" -ItemType File -Value "The site is temporarily offline for updates."
      shell: powershell

    - name: Publish Qoip-Web
      run: dotnet publish Qoip/Qoip-Web/Qoip-Web.csproj -c Release -o "${{ secrets.DEPLOY_PATH }}"

    - name: Bring Application Back Online
      run: Remove-Item -Path "${{ secrets.DEPLOY_PATH }}/app_offline.htm" -Force
      shell: powershell

      